config/routes.rb
WeHearNebraska::Application.routes.draw do
  resources :posts


  resources :tweets

  root to: 'home#show'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  get 'sent', to: 'home#sent', as: 'sent'
  
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :tweets, only: [:new, :create]
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  
  get 'tweets/retweet-this', to: 'tweets#retweet_this', as: 'retweet'
  get 'tweets/unretweet-this', to: 'tweets#unretweet_this', as: 'unretweet'
  
  get 'tweets/ban', to: 'tweets#ban', as: 'ban'
  
  get 'tweets/favorite-this', to: 'tweets#favorite_this', as: 'favorite'
  get 'tweets/unfavorite-this', to: 'tweets#unfavorite_this', as: 'unfavorite'
  
  get 'tweets/profpic', to: 'tweets#profpic', as: 'profpic'
  
  get 'posts/:id/approve', to: 'posts#approve', as: 'approve'
  get 'posts/:id/unapprove', to: 'posts#unapprove', as: 'unapprove'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if current_user
      if current_user.name == "Hear Nebraska"
        @tweets = Post.order("created_at DESC")
      else
        @tweets = Post.where(approved: true).order("created_at DESC")
      end
    else
      @tweets = Post.where(approved: true).order("created_at DESC")
    end
  end
  
  def sent
    if current_user
      if current_user.name == "Hear Nebraska"
        @tweets = Post.order("created_at DESC")
      else
        @tweets = Post.where(approved: true).order("created_at DESC")
      end
    else
      @tweets = Post.where(approved: true).order("created_at DESC")
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/sent.html.erb
<div class="body">
    <div class="body--background">
        <div class="background--container">
            <div class="container--donate">
                <a href="https://www.omahagives24.org/index.php?section=organizations&action=newDonation&fwID=944" target="_blank">
                    <div class="donate--call-to-action">
                        <% if current_user %>
                            <strong>Donate to Hear Nebraska today. We're working to make our state a cultural destination.</strong>
                        <% else %>
                            <strong>Donate to Hear Nebraska today. We're working to make our state a cultural destination.</strong>
                        <% end %>
                    </div>
                </a>
            </div>
            <header class="container--header">
                <div class="header--sent">
                    <h1 class="sent--text"><em>Tweet sent and submitted<br class="line-break"> for approval below.</em></h1>
                    <a href="/">
                        <div class="sent--button">
                            TWEET AGAIN
                        </div>
                    </a>
                    <a href="https://www.omahagives24.org/index.php?section=organizations&action=newDonation&fwID=944" target="_blank">
                        <div class="sent--button">
                            DONATE TO HN
                        </div>
                    </a>
                    <% if current_user %>
                    <div class="sent--login-status">
                        <div class="login-status--status">
                            <em>You are logged in as <%= current_user.name %>. 
                                <a href="/signout">
                                    Click here to logout.
                                </a>
                            </em>
                        </div>
                    </div>
                    <% end %>
                </div>
            </header>
            <div class="container--photo-credit">
                <div class="photo-credit--credit">
                    <em>photo of <a href="http://hearnebraska.org/feature/avett-brothers-pershing-center-photo-slideshow/" target="_blank">The Avett Brothers</a> by Matthew Masin</em>
                </div>
            </div>
            <main class="container--tweets">
                <% if @tweets.count != 0 %>
                    <% @tweets.each do |tweet| %>
                        <div class="tweets--tweet">
                            <div class="tweet--profile-image">
                                <a href="http://twitter.com/<%= tweet.username %>" target="_blank">
                                    <img src="<%= tweet.photo %>" width="20px" alt="profile_image"/>
                                </a>
                            </div>
                            <div class="tweet--content">
                                <h4 class="content--handle"><%= tweet.full_name %>&nbsp;&nbsp; 
                                    <a href="http://twitter.com/<%= tweet.username %>">
                                        <div>
                                            <em>@<%= tweet.username %></em>
                                        </div>
                                    </a>
                                </h4>
                                <p class="content--text">
                                    <%= simple_format(tweet.text.encode) %>
                                </p>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <div class="tweets--tweet">
                        <div class="tweet--profile-image">
                            <a href="http://twitter.com/hearnebraska" target="_blank">
                                <img src="https://pbs.twimg.com/profile_images/481163467903078400/OaHZmk1J.png" width="20px" alt="profile_image"/>
                            </a>
                        </div>
                        <div class="tweet--content">
                            <h4 class="content--handle">Hear Nebraska 
                                <a href="http://twitter.com/hearnebraska">
                                    <div>
                                        <em>@hearnebraska</em>
                                    </div>
                                </a>
                            </h4>
                            <p class="content--text">
                                Be the first to ask a band to tour Nebraska. Sign in, and tell them to play above.
                            </p>
                        </div>
                    </div>
                <% end %>
            </main>
            <div class="container--donate">
                <div class="donate--logo">
                    <div class="logo--image">
                        <a href="https://www.hearnebraska.org">
                            <%= image_tag("hn-logo.png", srcset: "assets/hn-logo.png 1x, assets/hn-logo_2x.png 2x, assets/hn-logo_3x.png 3x", alt: "Hear Nebraska") %>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/show.html.erb
<div class="body">
    <% if flash[:notice] %>
        <div class="body--notice"><%= flash[:notice] %></div>
    <% end %>
    <div class="body--background">
        <div class="background--container">
            <div class="container--donate">
                <a href="https://www.omahagives24.org/index.php?section=organizations&action=newDonation&fwID=944" target="_blank">
                    <div class="donate--call-to-action">
                        <% if current_user %>
                            <strong>Donate to Hear Nebraska today. We're working to make our state a cultural destination.</strong>
                        <% else %>
                            <strong>It's up to us to make Nebraska a destination for touring bands.</strong>
                        <% end %>
                    </div>
                </a>
            </div>
            <header class="container--header" id="band-image">
                <div class="header--question">
                    <% unless current_user %>
                        <h1 class="question--text"><em>Because silence won't convince them.</em></h1>
                    <% else %>
                        <h1 class="question--text"><em>Tell your favorite band to play Nebraska.</em></h1>
                    <% end %>
                    <%= form_for :tweet, url: tweets_path, method: :post do |f| %>
                        <% if current_user %>
                            <div class="question--input">
                                <%= f.text_field :band, :placeholder => "@BandHandle", :value => "#{@band}", :class => "input--band" %>
                                <%= f.text_field :message, :placeholder => "Please play Nebraska because...", :value => "#{@message}", :class => "input--message" %>
                                <span class="question--characters-left">79</span>
                            </div>
                        <% else %>
                            <div class="question--sign-in-message">
                                <a href="/auth/twitter">Sign into Twitter, and tell your favorite band to play a show in our state.</a>
                            </div>
                        <% end %>
                        <% if current_user %>
                            <%= f.submit "TWEET", :id => "submit" %>
                        <% else %>
                            <%= link_to "SIGN IN", "/auth/twitter", id: "sign-in" %>
                        <% end %>
                    <% end %>
                    <% if current_user %>
                    <div class="question--login-status">
                        <div class="login-status--status">
                            <em>You are logged in as <%= current_user.name %>. 
                                <a href="/signout">
                                    Click here to logout.
                                </a>
                            </em>
                        </div>
                    </div>
                    <% end %>
                </div>
            </header>
            <div class="container--photo-credit">
                <div class="photo-credit--credit">
                    <em>photo of <a href="http://hearnebraska.org/feature/avett-brothers-pershing-center-photo-slideshow/" target="_blank">The Avett Brothers</a> by Matthew Masin</em>
                </div>
            </div>
            <main class="container--tweets">
                <% if @tweets.count != 0 %>
                    <% @tweets.each do |tweet| %>
                        <div class="tweets--tweet">
                            <div class="tweet--profile-image">
                                <a href="http://twitter.com/<%= tweet.username %>" target="_blank">
                                    <img src="<%= $twitter.user(tweet.username).profile_image_uri(size = :bigger) %>" width="20px" alt="profile_image"/>
                                </a>
                            </div>
                            <div class="tweet--content">
                                <h4 class="content--handle"><%= tweet.full_name %>&nbsp;&nbsp; 
                                    <a href="http://twitter.com/<%= tweet.username %>">
                                        <div>
                                            <em>@<%= tweet.username %></em>
                                        </div>
                                    </a>
                                </h4>
                                <p class="content--text">
                                    <%= simple_format(auto_link(tweet.text.encode)) %>
                                </p>
                                <% if current_user %>
                                    <% if current_user.name == "Hear Nebraska" %>
                                        <div class="content--approval">
                                            <% if tweet.approved != true %>
                                                <a href="/posts/<%= tweet.id %>/approve"><p>Approve</p></a>
                                            <% else %>
                                                <a href="/posts/<%= tweet.id %>/unapprove"><p>Unapprove</p></a>
                                            <% end %>
                                        </div>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <div class="tweets--tweet">
                        <div class="tweet--profile-image">
                            <a href="http://twitter.com/hearnebraska" target="_blank">
                                <img src="https://pbs.twimg.com/profile_images/481163467903078400/OaHZmk1J.png" width="20px" alt="profile_image"/>
                            </a>
                        </div>
                        <div class="tweet--content">
                            <h4 class="content--handle">Hear Nebraska 
                                <a href="http://twitter.com/hearnebraska">
                                    <div>
                                        <em>@hearnebraska</em>
                                    </div>
                                </a>
                            </h4>
                            <p class="content--text">
                                Be the first to ask a band to tour Nebraska. Sign in, and tell them to play above.
                            </p>
                        </div>
                    </div>
                <% end %>
            </main>
            <div class="container--donate">
                <div class="donate--logo">
                    <div class="logo--image">
                        <a href="https://www.hearnebraska.org">
                            <%= image_tag("hn-logo.png", srcset: "assets/hn-logo.png 1x, assets/hn-logo_2x.png 2x, assets/hn-logo_3x.png 3x", alt: "Hear Nebraska") %>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>